set(_CATKIN_CURRENT_PACKAGE "moveit_quantec")
set(moveit_quantec_VERSION "1.0.0")
set(moveit_quantec_MAINTAINER " <TODO@email.com>")
set(moveit_quantec_PACKAGE_FORMAT "2")
set(moveit_quantec_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(moveit_quantec_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(moveit_quantec_BUILDTOOL_DEPENDS "catkin")
set(moveit_quantec_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_quantec_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(moveit_quantec_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(moveit_quantec_TEST_DEPENDS )
set(moveit_quantec_DOC_DEPENDS )
set(moveit_quantec_URL_WEBSITE "")
set(moveit_quantec_URL_BUGTRACKER "")
set(moveit_quantec_URL_REPOSITORY "")
set(moveit_quantec_DEPRECATED "")