position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - motor_1
    - motor_2
    - motor_3
    - motor_4
    - motor_5
    - motor_6
  gains:
    motor_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1