joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

  controller_list:
    -name: /bdr_ur10/arm_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joint: 
      -base_link
      -shoulder_link
      -upper_arm_link
      -forearm_link
      -wrist_1_link
      -wrist_2_link
      -wrist_3_link