controller_list:
  - name: fake_ur10_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_quantec_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_ft_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_camera_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: ur10_manipulator
    pose: ur10_home
  - group: quantec_manipulator
    pose: quantec_home