set(_CATKIN_CURRENT_PACKAGE "tars_robot")
set(tars_robot_VERSION "0.0.0")
set(tars_robot_MAINTAINER "vscode <vscode@todo.todo>")
set(tars_robot_PACKAGE_FORMAT "2")
set(tars_robot_BUILD_DEPENDS "dynamic_reconfigure" "geometry_msgs" "moveit_core" "moveit_ros_planning_interface" "moveit_visual_tools" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "tf2")
set(tars_robot_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "geometry_msgs" "moveit_core" "moveit_ros_planning_interface" "moveit_visual_tools" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "tf2")
set(tars_robot_BUILDTOOL_DEPENDS "catkin")
set(tars_robot_BUILDTOOL_EXPORT_DEPENDS )
set(tars_robot_EXEC_DEPENDS "dynamic_reconfigure" "geometry_msgs" "moveit_core" "moveit_ros_planning_interface" "moveit_visual_tools" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "tf2")
set(tars_robot_RUN_DEPENDS "dynamic_reconfigure" "geometry_msgs" "moveit_core" "moveit_ros_planning_interface" "moveit_visual_tools" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "tf2")
set(tars_robot_TEST_DEPENDS )
set(tars_robot_DOC_DEPENDS )
set(tars_robot_URL_WEBSITE "")
set(tars_robot_URL_BUGTRACKER "")
set(tars_robot_URL_REPOSITORY "")
set(tars_robot_DEPRECATED "")