ur10_manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1 #0.005
  position_only_ik: false ##new
  solve_type: Distance ##new
  goal_joint_tolerance: 0.1
  goal_position_tolerance: 0.1
  goal_orientation_tolerance: 0.1
quantec_manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1 #0.005
  position_only_ik: false ##new
  solve_type: Distance ##new
  goal_joint_tolerance: 0.1
  goal_position_tolerance: 0.1
  goal_orientation_tolerance: 0.1