ur10_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 20000
      d: 500
      i: 10
      i_clamp: 1
    shoulder_lift_joint:
      p: 20000
      d: 500
      i: 10
      i_clamp: 1
    elbow_joint:
      p: 20000
      d: 500
      i: 10
      i_clamp: 1
    wrist_1_joint:
      p: 500
      d: 10
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 500
      d: 10
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 10
      d: 0.1
      i: 0
      i_clamp: 1
quantec_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  gains:
    joint_1:
      p: 20000
      d: 500
      i: 10
      i_clamp: 1
    joint_2:
      p: 20000
      d: 500
      i: 1
      i_clamp: 1
    joint_3:
      p: 20000
      d: 500
      i: 1
      i_clamp: 1
    joint_4:
      p: 500
      d: 10
      i: 1
      i_clamp: 1
    joint_5:
      p: 500
      d: 10
      i: 1
      i_clamp: 1
    joint_6:
      p: 10
      d: 0.1
      i: 0
      i_clamp: 1