set(_CATKIN_CURRENT_PACKAGE "bdr11_description")
set(bdr11_description_VERSION "0.0.0")
set(bdr11_description_MAINTAINER "robat <robat@todo.todo>")
set(bdr11_description_PACKAGE_FORMAT "2")
set(bdr11_description_BUILD_DEPENDS )
set(bdr11_description_BUILD_EXPORT_DEPENDS )
set(bdr11_description_BUILDTOOL_DEPENDS "catkin")
set(bdr11_description_BUILDTOOL_EXPORT_DEPENDS )
set(bdr11_description_EXEC_DEPENDS )
set(bdr11_description_RUN_DEPENDS )
set(bdr11_description_TEST_DEPENDS )
set(bdr11_description_DOC_DEPENDS )
set(bdr11_description_URL_WEBSITE "")
set(bdr11_description_URL_BUGTRACKER "")
set(bdr11_description_URL_REPOSITORY "")
set(bdr11_description_DEPRECATED "")